### ISSUE TITLE
Ideal SHeX for CIDOC-CRM

### ISSUE THREAD

**Issue by mzeinstra** [weso/SAF-Lux#12]
I need a SHeX file of the CIDOC-CRM implementation of the DMG so WP5 can work on importscripts.

**Comment by labra** [comment]
I have changed the E82_Actor_Appellation by E41_Appellation.

The main pending task is to add source of information and review the lines that have changed. I expect to do it next week.

**Comment by mzeinstra** [comment]
Hi @labra could you point to the document where you made these changes?

**Comment by labra** [comment]
It will be [here](https://github.com/weso/SAF-Lux/blob/main/shex/rules_1.0.1.shex)

**Comment by labra** [comment]
I have updated the file to adapt to the contents of the Excel sheet. 

- Removed the line numbers because they were difficult to maintain as it is easy to add/remove lines in Excel, but keeping track of those changes in the ShEx file is a very error-prone.
- Joined all the source of information in a single shape because it makes the ShEx file more maintainable and follow the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle.
- Adopted EDTF datatypes namespace for dates. I think the right namespace for EDTF is [http://id.loc.gov/datatypes/edtf/](http://id.loc.gov/datatypes/edtf/) which defines the [edtf:EDTF](http://id.loc.gov/datatypes/edtf/EDTF) datatype.
- Separated most of the top-level definitions using shape references to increase readability
- Represents alternative name/numeration/title using the property `crm:P139_has_alternative_form` from the appellation name. This follows the PDF figure and makes sense as alternative names are alternative appellations to some appellation. This is different to the representation we had in the paper.

It may require some further review to check consistency, but I think we can close this issue and open some specific issues for the next problems/changes we find.
