### ISSUE TITLE
E82 Actor appellation vs. E41 Appellation

### ISSUE THREAD

**Issue by joelthill** [weso/SAF-Lux#42]
According to Michelle, it has been agreed to fully adopt CIDOC-CRM 7.1.1 vocabulary (instead of 6.2).
This would (as far as I can see at least) require a switch from "E41 Appllation" to "E82 Actor appellation".

---

here:

saflux:NameAppellation {
    rdf:type                       [ **crm:E41_Appellation** ]           ;
    efr:R8_consists_of             @saflux:Name                         ;
    efr:R8_consists_of             @saflux:Numeration                 ? ;
    efr:R8_consists_of             @saflux:Title                      ? ;
    crm:P70i_is_documented_in      @saflux:SourceOfInformation        * ;
    crm:P139_has_alternative_form  @saflux:AlternativeNameAppellation * ;
}

saflux:NameType {
  rdf:type   [ crm:E55_Type ] ;
  saflux:value  @saflux:CL3_Name_Format
}

and here:

saflux:AlternativeNameAppellation {
  rdf:type                  [ **crm:E41_Appellation** ]           ;
  efr:R8_consists_of        @saflux:AlternativeName            ? ;
  efr:R8_consists_of        @saflux:AlternativeNumeration      ? ;
  efr:R8_consists_of        @saflux:AlternativeTitle           ? ;
  crm:P70i_is_documented_in @saflux:SourceOfInformation        * ;
}

---

j.

**Comment by labra** [comment]
Yes, the version is CIDOC-CRM 7.1.1 and indeed we changed from E82_Actor_Appellation to E41_Appellation because the former is the one that I think is deprecated according to the [CIDOC-CRM spec](http://cidoc-crm.org/version/version-7.1.1), table 5 in Appendix (page 170).

Maybe, I read it wrong, but I understand that E82_Actor_Appellation is deprecated and should be replaced by E41_Appellation. 

We did that replacement in the different files. Can you confirm if it is OK or maybe we miss something?

**Comment by joelthill** [comment]
Clarified today with Michelle - you're right. no change required.
